# Generated by Django 5.0.7 on 2024-10-29 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_continents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description1', models.CharField(max_length=900)),
                ('description2', models.CharField(max_length=900)),
                ('description3', models.CharField(max_length=900)),
                ('image1', models.CharField(max_length=900)),
                ('image2', models.CharField(max_length=900)),
                ('image3', models.CharField(max_length=900)),
                ('image4', models.CharField(max_length=900)),
                ('price', models.FloatField(default=0)),
                ('isActive', models.BooleanField(default=True)),
                ('Booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site', to='first.continents')),
                ('watchlist', models.ManyToManyField(blank=True, null=True, related_name='listingwatchlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
