# Generated by Django 5.0.7 on 2024-11-01 14:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_travel'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='title2',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
    ]
