# Generated by Django 5.0.7 on 2024-11-01 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_travel_title2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='title2',
        ),
    ]
