# Generated by Django 5.0.7 on 2024-11-01 14:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_remove_travel_watchlist_travel_month_departure'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='listingwatchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
