# Generated by Django 5.0.7 on 2024-11-01 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0008_month_remove_travel_month_departure'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='date', to='first.month'),
        ),
    ]
