# Generated by Django 5.0.7 on 2024-11-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0009_travel_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='time',
        ),
        migrations.AddField(
            model_name='travel',
            name='time',
            field=models.ManyToManyField(blank=True, null=True, related_name='date', to='first.month'),
        ),
    ]
