# Generated by Django 5.0.7 on 2024-11-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0011_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='month_trip',
            field=models.CharField(max_length=900, null=True),
        ),
    ]
