# Generated by Django 5.0.7 on 2024-11-08 16:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0012_alter_booking_month_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='Booking',
        ),
        migrations.AddField(
            model_name='travel',
            name='booking_user',
            field=models.ManyToManyField(blank=True, null=True, related_name='BOOKED', to=settings.AUTH_USER_MODEL),
        ),
    ]
