# Generated by Django 5.0.7 on 2024-11-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0014_travel_description4_travel_description5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='short_description',
            field=models.CharField(max_length=900, null=True),
        ),
    ]
